### ISSUE TITLE
Issue while running sample testcase of login

### ISSUE THREAD

**Issue by salmanchauhan** [PoojaGugu/SAPGeneric#2]
Hi @PoojaGugu ,

After following instructions I tried to run sample testcase but its giving following error. your inputs will be highly appreciated.

[RemoteTestNG] detected TestNG version 6.9.6
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.testng.xml.XMLParser (file:/C:/Users/svchauhan/.m2/repository/org/testng/testng/6.9.6/testng-6.9.6.jar) to constructor com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl()
WARNING: Please consider reporting this to the maintainers of org.testng.xml.XMLParser
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[TestNG] Running:
  C:\Users\svchauhan\AppData\Local\Temp\testng-eclipse-1607516130\testng-customsuite.xml

**FAILED: LoginSAPGUI
com.jacob.com.ComFailException: A COM exception has been encountered:
At Invoke of: text
Description: 80010105 / The server threw an exception.**

	at com.jacob.com.Dispatch.invokev(Native Method)
	at com.jacob.com.Dispatch.invokev(Dispatch.java:625)
	at com.jacob.com.Dispatch.invoke(Dispatch.java:498)
	at com.jacob.com.Dispatch.put(Dispatch.java:580)
	at com.jacob.activeX.ActiveXComponent.setProperty(ActiveXComponent.java:239)
	at com.jacob.activeX.ActiveXComponent.setProperty(ActiveXComponent.java:261)
	at com.library.generic.SAPGeneric.SAPGUITextFieldSet(SAPGeneric.java:69)
	at com.library.generic.SAPGeneric.SAPGUITextFieldSet(SAPGeneric.java:116)
	at com.Samples.Login.LoginSAPGUI(Login.java:70)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

===============================================
    Default test
    Tests run: 1, Failures: 1, Skips: 0
===============================================

===============================================
Default suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================

[TestNG] Time taken by org.testng.reporters.jq.Main@52f759d7: 93 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@543c6f6d: 24 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 14 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@75881071: 27 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@2db7a79b: 268 ms
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@17d0685f: 16 ms

**Comment by PoojaGugu** [comment]
Hi
Please check the pom xml testng version  and eclipse plugin version
Sap gui scriptin should be enabled
Thanks
Venkata Siva Kumar

**Comment by salmanchauhan** [comment]
![image](https://user-images.githubusercontent.com/6511815/66985551-a5ff0080-f0da-11e9-816a-f3dcf4f48a9a.png)

@PoojaGugu 

Versions of testng and eclipse plugin are proper.

**While trying to enter username in this field it is throwing this exception : FAILED: LoginSAPGUI
com.jacob.com.ComFailException: A COM exception has been encountered:
At Invoke of: text**
Description: 80010105 / The server threw an exception.

refer this detailed logs:

[RemoteTestNG] detected TestNG version 6.9.6
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.testng.xml.XMLParser (file:/C:/Users/svchauhan/.m2/repository/org/testng/testng/6.9.6/testng-6.9.6.jar) to constructor com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl()
WARNING: Please consider reporting this to the maintainers of org.testng.xml.XMLParser
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[TestNG] Running:
  C:\Users\svchauhan\AppData\Local\Temp\testng-eclipse-1249324706\testng-customsuite.xml

FAILED: LoginSAPGUI
com.jacob.com.ComFailException: A COM exception has been encountered:
At Invoke of: text
Description: 80010105 / The server threw an exception.

	at com.jacob.com.Dispatch.invokev(Native Method)
	at com.jacob.com.Dispatch.invokev(Dispatch.java:625)
	at com.jacob.com.Dispatch.invoke(Dispatch.java:498)
	at com.jacob.com.Dispatch.put(Dispatch.java:580)
	at com.jacob.activeX.ActiveXComponent.setProperty(ActiveXComponent.java:239)
	at com.jacob.activeX.ActiveXComponent.setProperty(ActiveXComponent.java:261)
	**at com.library.generic.SAPGeneric.SAPGUITextFieldSet(SAPGeneric.java:69)
	at com.library.generic.SAPGeneric.SAPGUITextFieldSet(SAPGeneric.java:116)
	at com.Samples.Login.LoginSAPGUI(Login.java:70)**
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)


===============================================
    Default test
    Tests run: 1, Failures: 1, Skips: 0
===============================================


===============================================
Default suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================

[TestNG] Time taken by org.testng.reporters.jq.Main@52f759d7: 195 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@543c6f6d: 32 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 15 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@75881071: 6 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@2db7a79b: 76 ms
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@17d0685f: 17 ms

**Comment by PoojaGugu** [comment]
Please record using sapgui script generator check object class name

Still if have issue we will have call

**Comment by salmanchauhan** [comment]
we can surely have a call please connect me on skype: salmankhan.chauhan is my id. thanks in advance.

**Comment by PoojaGugu** [comment]
Is it Windows 64bit. Then need to update registry steps are mentioned in
document

**Comment by salmanchauhan** [comment]
@PoojaGugu yes, I have followed steps first while setting up.

**Comment by PoojaGugu** [comment]
Please check once again

**Comment by salmanchauhan** [comment]
@PoojaGugu  please refer following screenshot for your reference

<img width="745" alt="sc1" src="https://user-images.githubusercontent.com/6511815/67293810-90d30900-f502-11e9-8a63-574bff6011ea.png">

**Comment by PoojaGugu** [comment]
Restarted

**Comment by salmanchauhan** [comment]
@PoojaGugu  Still no success.

**Comment by salmanchauhan** [comment]
@PoojaGugu Could you please help me to solve this issue.

**Comment by salmanchauhan** [comment]
Working with the latest version Thanks for all your support. 👍

**Comment by PoojaGugu** [comment]
Thanks you
